export const Images = {
   arrowback : require('../assets/arrowleft.png'),
   mainbackground:require('../assets/background2.png'),
   logo:require('../assets/logo.png'),
   art3: require('../assets/art3.png'),
   at:require('../assets/at.png'),
   lock:require('../assets/lock.png'),
   arrowright:require('../assets/right2.png'),
   art1: require('../assets/art1.png'),
   art4:require('../assets/art4.png'),
   art2:require('../assets/art2.png'),
   wallet:require('../assets/wallet.png'),
   history:require('../assets/history1.png'),
   merchants:require('../assets/cowboy.png'),
   user:require('../assets/user.png'),
   arrows:require('../assets/arrows.png'),
   add:require('../assets/circle.png'),
   scanner:require('../assets/scanner2.png'),
   plus:require('../assets/plus.png'),
   setting:require('../assets/setting3.png'),
   copy:require('../assets/paste.png'),
   send:require('../assets/send.png'),
   receive:require('../assets/receive.png'),
   receive2x:require('../assets/Received2x.png'),
   buy:require('../assets/buy.png'),
   BTC:require('../assets/BTC.png'),
   eth:require('../assets/eth.png'),
   tether:require('../assets/tether.png'),
   pic:require('../assets/pic.png'),
   wallet3:require('../assets/wallet3.png'),
   error:require('../assets/error.png'),
   BTN: require('../assets/BTN.png'),
   polygon:require('../assets/polygon.png'),
   send2:require('../assets/send2.png'),
   Recevied:require('../assets/Received.png'),
   Deposit:require('../assets/Deposit.png'),
   downarrow:require('../assets/downarrow.png'),
   scan2:require('../assets/scan2.png') ,
   arrow:require('../assets/arrow.png'),
   check:require('../assets/check.png'),
   search:require('../assets/search.png'),
   capman:require('../assets/capman.png'),
   lockdark:require('../assets/lockicon.png'),
   profile:require('../assets/profile.png'),
   walletdark:require('../assets/walleticon.png'),
   arrowicon:require('../assets/arrowicon.png'),
   bell:require('../assets/bel.png'),
   close:require('../assets/close.png'),
   send2x:require('../assets/send2x.png'),
   qr:require('../assets/scanimg.png'),
   share:require('../assets/share.png'),
   logout:require('../assets/logout.png'),
   phone:require('../assets/phone.png'),
   dummyprofile:require('../assets/dummy-profile.png')

}