export const API_URLS = {
  LOGIN: 'auth/login',
  SIGN_UP: 'auth/register',
  VERIFY_EMAIL:'member/verifycode', 
  RESEND_CODE:'member/resendCode',
  FORGOT_PASSWORD:'auth/forgetpassword',
  UPDATE_PASSWORD:'member/updatepassword',
  FCM_SUBSCRIBE: 'push/subscribe',
  CHANGE_PASSWORD: 'change-password',
  MY_POSTED_NEEDS: '/needs/my-posted-needs',
  NEEDS_LIST: 'needs/list',
  NEEDS_POST: 'needs/post',
  CATEGORIES: 'categories',
  UPDATE_PROFILE: 'update-profile',
}