export const API_URLS = {
  LOGIN: 'signin',
  SIGN_UP: 'signup',
  VERIFY_EMAIL: 'verify_account',
  RESEND_CODE: 'resend_account_verification_email',
  FORGOT_PASSWORD: 'forgot_password',
  UPDATE_PASSWORD: 'change_password',
  FCM_SUBSCRIBE: 'push/subscribe',
  CHANGE_PASSWORD: 'reset_password',
  MY_PROFILE: "my_profile",
  PUSH_NOTIFICATION_STATUS: 'push_notification_status',
  SMS_NOTIFICATION_STATUS: 'sms_notification_status',
  PROMOTIONAL_NOTIFICATION_STATUS: 'promotional_notification_status',
  UPLOAD_IMAGE: 'upload_image',
  Generate_Access_Token_From_Refresh_Token: "generate_access_token_from_refresh_token",
  GENERATE_2FA: 'generate_2FA',
  UPDATE_2FA: 'update_2FA',
  VERIFY_2FA: "verify_2fa",
  CATEGORIES: 'categories',
  UPDATE_PROFILE: 'edit_profile',
  Generate_Otp_For_Profile: "generate_otp_for_profile",
  Exchange_Crypto_Currencies: 'exchange/fetch_available_crypto_currencies',
  Exchange_Transaction: 'exchange/transaction'
}